import os
import json
import uuid
from typing import List, Dict, Any
from app.services.data_service import DataService
from app.config import settings

class JupyterService:
    """
    Compiles an Action Ledger into a Kaggle-style Jupyter Notebook (.ipynb).
    """

    @staticmethod
    def generate_notebook(dataset_id: str) -> str:
        """
        Generates a Jupyter Notebook based on the user's recorded actions
        and basic EDA/ML boilerplate. Returns the path to the .ipynb file.
        """
        dataset_info = DataService.get_dataset_info(dataset_id)
        ledger = DataService.get_action_ledger(dataset_id)
        dataset_name = dataset_info.get("filename", "dataset.csv")

        cells = []
        
        # Helper to add markdown cells
        def add_md(text: str):
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [text]
            })

        # Helper to add code cells
        def add_code(code: str):
            cells.append({
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [code]
            })

        # 1. Header
        add_md(f"# 📊 DataMind AI: Automated Analysis Notebook\n\nThis notebook was automatically generated by DataMind AI based on the interactive data cleaning and analysis you performed on `{dataset_name}`. It contains all the necessary preprocessing, exploratory data analysis (EDA), and basic model setup steps.")

        # 2. Imports
        add_md("## 1. Environment Setup & Imports\nImporting the necessary standard libraries for data manipulation, visualization, and machine learning.")
        add_code("import numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport warnings\n\nwarnings.filterwarnings('ignore')\n%matplotlib inline\n\n# Configure visual styling\nsns.set_theme(style='darkgrid', palette='muted')")

        # 3. Data Loading
        add_md(f"## 2. Data Loading\nLoading `{dataset_name}` into a Pandas DataFrame.")
        # In a real environment, the user would update this path.
        add_code(f"file_path = '{dataset_name}' # Update this path to where your dataset is stored locally.\ndf = pd.read_csv(file_path)\n\n# Display basic information\ndf.info()\ndisplay(df.head())")

        # 4. Data Cleaning (From Ledger)
        add_md("## 3. Data Preprocessing & Cleaning\nReplaying the exact cleaning operations performed in the DataMind UI.")
        
        cleaning_code_lines = []
        if not ledger:
            cleaning_code_lines.append("# No specific cleaning operations were performed in the UI.")
        
        for idx, step in enumerate(ledger):
            action = step["action"]
            p = step["params"]
            cleaning_code_lines.append(f"\n# Step {idx+1}: {action}")
            
            if action == "missing_values":
                strat = p.get("strategy")
                cols = p.get("columns")
                cols_str = f"df.columns" if not cols else str(cols)
                if strat == "drop_rows":
                    cleaning_code_lines.append(f"df = df.dropna(subset={cols_str})")
                elif strat == "drop_cols":
                    cleaning_code_lines.append(f"df = df.drop(columns={cols_str})")
                elif strat == "fill_mean":
                    cleaning_code_lines.append(f"for col in {cols_str}:\n    if pd.api.types.is_numeric_dtype(df[col]):\n        df[col] = df[col].fillna(df[col].mean())")
                elif strat == "fill_median":
                    cleaning_code_lines.append(f"for col in {cols_str}:\n    if pd.api.types.is_numeric_dtype(df[col]):\n        df[col] = df[col].fillna(df[col].median())")
                elif strat == "fill_mode":
                    cleaning_code_lines.append(f"for col in {cols_str}:\n    mode_val = df[col].mode()\n    if not mode_val.empty:\n        df[col] = df[col].fillna(mode_val.iloc[0])")
                elif strat == "fill_constant":
                    cleaning_code_lines.append(f"df[{cols_str}] = df[{cols_str}].fillna({repr(p.get('fill_value'))})")
                else:
                    cleaning_code_lines.append(f"# Applied missing value strategy: {strat} on {cols_str}")

            elif action == "remove_duplicates":
                subset = p.get("subset")
                cleaning_code_lines.append(f"df = df.drop_duplicates(subset={subset})")

            elif action == "drop_columns":
                cleaning_code_lines.append(f"df = df.drop(columns={p.get('columns')})")

            elif action == "rename_columns":
                cleaning_code_lines.append(f"df = df.rename(columns={p.get('rename_map')})")

            elif action == "convert_dtype":
                cleaning_code_lines.append(f"df['{p.get('column')}'] = df['{p.get('column')}'].astype('{p.get('target_dtype')}')")

            elif action == "handle_outliers":
                cleaning_code_lines.append(f"# Handled outliers for {p.get('column')} using {p.get('method')} ({p.get('strategy')})")
                if p.get('strategy') == 'remove':
                    cleaning_code_lines.append(f"# Removing {p.get('column')} outliers...")

            elif action == "normalize":
                cleaning_code_lines.append(f"# Normalized {p.get('columns')} using {p.get('method')} scaler")

            elif action == "encode_column":
                cleaning_code_lines.append(f"# Encoded categorical column {p.get('column')} using {p.get('method')} encoding")

            else:
                cleaning_code_lines.append(f"# Operation {action} applied with params {p}")

        add_code("\n".join(cleaning_code_lines))

        # 5. EDA Visualizations
        add_md("## 4. Exploratory Data Analysis (EDA)\nAutomatically generating necessary visualizations to understand distributions, missing values, and correlations.")
        
        eda_code = (
            "# Missing Values Heatmap\n"
            "plt.figure(figsize=(10, 6))\n"
            "sns.heatmap(df.isnull(), yticklabels=False, cbar=False, cmap='viridis')\n"
            "plt.title('Missing Values Distribution')\n"
            "plt.show()\n\n"
            "# Distribution of Numerical Features\n"
            "numerical_cols = df.select_dtypes(include=np.number).columns\n"
            "if len(numerical_cols) > 0:\n"
            "    df[numerical_cols].hist(figsize=(15, 10), bins=20, edgecolor='black')\n"
            "    plt.suptitle('Histograms of Numerical Features')\n"
            "    plt.tight_layout()\n"
            "    plt.show()\n\n"
            "# Correlation Matrix Heatmap\n"
            "if len(numerical_cols) > 1:\n"
            "    plt.figure(figsize=(12, 8))\n"
            "    sns.heatmap(df[numerical_cols].corr(), annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)\n"
            "    plt.title('Correlation Matrix')\n"
            "    plt.show()"
        )
        add_code(eda_code)

        # Build Notebook Dictionary
        notebook = {
            "cells": cells,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "codemirror_mode": {"name": "ipython", "version": 3},
                    "file_extension": ".py",
                    "mimetype": "text/x-python",
                    "name": "python",
                    "nbconvert_exporter": "python",
                    "pygments_lexer": "ipython3",
                    "version": "3.8.0"
                }
            },
            "nbformat": 4,
            "nbformat_minor": 4
        }

        # Save to file
        reports_dir = settings.REPORTS_DIR
        os.makedirs(reports_dir, exist_ok=True)
        filename = f"datamind_analysis_{uuid.uuid4().hex[:8]}.ipynb"
        file_path = os.path.join(reports_dir, filename)

        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(notebook, f, indent=2)

        return file_path
